#pragma once

#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_NAME "Waite Design Labs"
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_NAME "WALL-Env OLED Sensor"
#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_ID 0xFFF1
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_ID 0x8000
#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING "1.7.0"
#define CHIP_DEVICE_CONFIG_DEFAULT_DEVICE_HARDWARE_VERSION_STRING "2.0"
