#pragma once

#include "sdkconfig.h"

#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_NAME "Waite Design Labs"
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_NAME "WALL-Env OLED Sensor"
#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_ID CONFIG_DEVICE_VENDOR_ID
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_ID CONFIG_DEVICE_PRODUCT_ID
#define CHIP_DEVICE_CONFIG_DEVICE_SOFTWARE_VERSION_STRING "1.2"
#define CHIP_DEVICE_CONFIG_DEFAULT_DEVICE_HARDWARE_VERSION_STRING "2.0"
